#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Admin/_ProductDetails.cshtml")]
    public partial class _Views_Admin__ProductDetails_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Application.Admin.ViewModel.ProductViewModel>
    {
        public _Views_Admin__ProductDetails_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("    ");

            
            #line 5 "..\..\Views\Admin\_ProductDetails.cshtml"
Write(Html.EditorForModel(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" style=\"position:relative;\"");

WriteLiteral(">\r\n            <label>Image</label>\r\n            <a");

WriteLiteral(" class=\'btn\'");

WriteLiteral(" href=\'javascript:;\'");

WriteLiteral(">\r\n                Select file...\r\n                <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" name=\"Image\"");

WriteLiteral(" size=\"40\"");

WriteLiteral("\r\n                       style=\"position:absolute;z-index:2;top:0;\r\n             " +
"                   left:0;filter: alpha(opacity=0); opacity:0;\r\n                " +
"                background-color:transparent;color:transparent;\"");

WriteLiteral("\r\n                       onchange=\'$(\"#upload-file-info\").html($(this).val());\'");

WriteLiteral(">\r\n            </a>\r\n            <span");

WriteLiteral(" class=\'label label-info\'");

WriteLiteral(" id=\"upload-file-info\"");

WriteLiteral("></span>\r\n        </div>\r\n");

            
            #line 20 "..\..\Views\Admin\_ProductDetails.cshtml"
        
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Admin\_ProductDetails.cshtml"
         if (Model != null && Model.ImageUrl != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <img");

WriteLiteral(" class=\"img-thumbnail\"");

WriteLiteral(" width=\"150\"");

WriteLiteral(" height=\"150\"");

WriteAttribute("src", Tuple.Create("\r\n                 src=\"", 917), Tuple.Create("\"", 956)
            
            #line 23 "..\..\Views\Admin\_ProductDetails.cshtml"
, Tuple.Create(Tuple.Create("", 941), Tuple.Create<System.Object, System.Int32>(Model.ImageUrl
            
            #line default
            #line hidden
, 941), false)
);

WriteLiteral(" />\r\n");

            
            #line 24 "..\..\Views\Admin\_ProductDetails.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"form-control-static\"");

WriteLiteral(">Нет картинки</div>\r\n");

            
            #line 28 "..\..\Views\Admin\_ProductDetails.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
