#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Admin/_ProductDetails.cshtml")]
    public partial class _Views_Admin__ProductDetails_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Application.Admin.ViewModel.ProductViewModel>
    {
        public _Views_Admin__ProductDetails_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"image-control row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-7\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"admin-card-img\"");

WriteLiteral(">\r\n");

            
            #line 6 "..\..\Views\Admin\_ProductDetails.cshtml"
            
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Admin\_ProductDetails.cshtml"
             if (Model != null && Model.ImageUrl != null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <img");

WriteLiteral(" class=\"img-thumbnail admin-pdp-image\"");

WriteAttribute("src", Tuple.Create(" src=\"", 294), Tuple.Create("\"", 315)
            
            #line 8 "..\..\Views\Admin\_ProductDetails.cshtml"
, Tuple.Create(Tuple.Create("", 300), Tuple.Create<System.Object, System.Int32>(Model.ImageUrl
            
            #line default
            #line hidden
, 300), false)
);

WriteLiteral(" />\r\n");

            
            #line 9 "..\..\Views\Admin\_ProductDetails.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <img");

WriteLiteral(" class=\"img-thumbnail admin-pdp-image\"");

WriteAttribute("src", Tuple.Create(" src=\"", 427), Tuple.Create("\"", 466)
, Tuple.Create(Tuple.Create("", 433), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/no-image-big.png")
, 433), false)
);

WriteLiteral(">\r\n");

            
            #line 13 "..\..\Views\Admin\_ProductDetails.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n        <div");

WriteLiteral(" class=\"input-group admin-pdp-image-form\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"input-group-prepend\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"input-group-text\"");

WriteLiteral(" href=\'javascript:;\'");

WriteLiteral(">Upload</a>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"custom-file\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" class=\"custom-file-input pdp-img\"");

WriteLiteral(" name=\"Image\"");

WriteLiteral("\r\n                       aria-describedby=\"inputGroupFileAddon01\"");

WriteLiteral(" onchange=\'$(\"#upload-file-info\").html($(this).val());\'");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"custom-file-label\"");

WriteLiteral(" id=\"upload-file-info\"");

WriteLiteral(">Choose file</label>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-5\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"admin-pdp\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 28 "..\..\Views\Admin\_ProductDetails.cshtml"
       Write(Html.EditorForModel(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
