#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Admin\ManageProducts.cshtml"
    using OmiconShop.WebUI.HtmlHelpers;

#line default
#line hidden
    using OmiconShop.WebUI;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Admin/ManageProducts.cshtml")]
    public partial class _Views_Admin_ManageProducts_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Application.Admin.ViewModel.ProductsListViewModel>
    {
        public _Views_Admin_ManageProducts_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Admin\ManageProducts.cshtml"
  
    ViewBag.Title = "ManageProducts";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<body>\r\n    <div>\r\n");

WriteLiteral("        ");

            
            #line 10 "..\..\Views\Admin\ManageProducts.cshtml"
   Write(Html.Action("Types", "Facet"));

            
            #line default
            #line hidden
WriteLiteral(";\r\n    </div>\r\n</body>\r\n\r\n");

            
            #line 14 "..\..\Views\Admin\ManageProducts.cshtml"
 foreach (var el in Model.Products)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"table table-hover\"");

WriteLiteral(">\r\n            <tr>\r\n                <td>");

            
            #line 19 "..\..\Views\Admin\ManageProducts.cshtml"
               Write(el.ProductId);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 20 "..\..\Views\Admin\ManageProducts.cshtml"
               Write(el.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 21 "..\..\Views\Admin\ManageProducts.cshtml"
               Write(el.Description);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 22 "..\..\Views\Admin\ManageProducts.cshtml"
               Write(el.Price);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td><button>Edit</button></td>\r\n            </tr>\r\n       " +
" </table>\r\n    </div>\r\n");

            
            #line 27 "..\..\Views\Admin\ManageProducts.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"btn-group pull-right\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 30 "..\..\Views\Admin\ManageProducts.cshtml"
Write(Html.PageLinks(Model.PagingInfo, x => Url.Action("ManageProducts", new { page = x })));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
