#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Admin\OrderDetails.cshtml"
    using Microsoft.AspNet.Identity;

#line default
#line hidden
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Admin/OrderDetails.cshtml")]
    public partial class _Views_Admin_OrderDetails_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Domain.Entities.Order>
    {
        public _Views_Admin_OrderDetails_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Admin\OrderDetails.cshtml"
  
    ViewBag.Title = "OrderDetails";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 8 "..\..\Views\Admin\OrderDetails.cshtml"
Write(Model.OrderId);

            
            #line default
            #line hidden
WriteLiteral(" Order</h2>\r\n\r\n");

            
            #line 10 "..\..\Views\Admin\OrderDetails.cshtml"
 if (User.Identity.IsAuthenticated)
{

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n");

WriteLiteral("        ");

            
            #line 13 "..\..\Views\Admin\OrderDetails.cshtml"
   Write(Html.RouteLink("Go to order list page", new { controller = "Admin", action = "OrderList" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 15 "..\..\Views\Admin\OrderDetails.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral(@"
<div>
    <table>
        <thead>
            <tr>
                <th>Order no.</th>
                <th>Order status</th>
                <th>Shipping method</th>
                <th>Payment method</th>
                <th>OrderDate</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>");

            
            #line 30 "..\..\Views\Admin\OrderDetails.cshtml"
               Write(Model.OrderId);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 31 "..\..\Views\Admin\OrderDetails.cshtml"
               Write(Model.Status);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 32 "..\..\Views\Admin\OrderDetails.cshtml"
               Write(Model.OrderInformation.Delivery);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 33 "..\..\Views\Admin\OrderDetails.cshtml"
               Write(Model.OrderInformation.Payment);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 34 "..\..\Views\Admin\OrderDetails.cshtml"
               Write(Model.OrderInformation.Date);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            </tr>\r\n        </tbody>\r\n    </table>\r\n</div>\r\n\r\n<div>\r\n    <t" +
"able>\r\n        <thead>\r\n            <tr>\r\n                <th>SHIP-TO ADDRESS</t" +
"h>\r\n            </tr>\r\n        </thead>\r\n        <tbody>\r\n            <tr>");

            
            #line 48 "..\..\Views\Admin\OrderDetails.cshtml"
           Write(Model.User.UserAddress.Address);

            
            #line default
            #line hidden
WriteLiteral("</tr>\r\n            <tr>");

            
            #line 49 "..\..\Views\Admin\OrderDetails.cshtml"
           Write(Model.User.UserAddress.Address2);

            
            #line default
            #line hidden
WriteLiteral("</tr>\r\n            <tr>");

            
            #line 50 "..\..\Views\Admin\OrderDetails.cshtml"
           Write(Model.User.UserAddress.City);

            
            #line default
            #line hidden
WriteLiteral("</tr>\r\n            <tr>");

            
            #line 51 "..\..\Views\Admin\OrderDetails.cshtml"
           Write(Model.User.UserAddress.Country);

            
            #line default
            #line hidden
WriteLiteral("</tr>\r\n            <tr>");

            
            #line 52 "..\..\Views\Admin\OrderDetails.cshtml"
           Write(Model.User.UserAddress.ZipCode);

            
            #line default
            #line hidden
WriteLiteral(@"</tr>
        </tbody>
    </table>
</div>

<div>
    <table>
        <thead>
            <tr>
                <th>Item no.</th>
                <th>Title</th>
                <th>Price</th>
                <th>Qty</th>
                <th>UOM</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
");

            
            #line 70 "..\..\Views\Admin\OrderDetails.cshtml"
            
            
            #line default
            #line hidden
            
            #line 70 "..\..\Views\Admin\OrderDetails.cshtml"
             foreach (var line in Model.BasketLine)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");

            
            #line 73 "..\..\Views\Admin\OrderDetails.cshtml"
                   Write(line.ProductId);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 74 "..\..\Views\Admin\OrderDetails.cshtml"
                   Write(line.Product.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 75 "..\..\Views\Admin\OrderDetails.cshtml"
                   Write(line.Product.Price);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 76 "..\..\Views\Admin\OrderDetails.cshtml"
                   Write(line.Qty);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 77 "..\..\Views\Admin\OrderDetails.cshtml"
                   Write(line.Uom);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 78 "..\..\Views\Admin\OrderDetails.cshtml"
                    Write(line.Qty * line.Product.Price);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");

            
            #line 80 "..\..\Views\Admin\OrderDetails.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n        <tfoot>\r\n            <tr>\r\n                <td");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(">Total $ ");

            
            #line 84 "..\..\Views\Admin\OrderDetails.cshtml"
                                   Write(Model.OrderInformation.Total);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </table>\r\n</div>\r\n\r\n<div>\r\n");

            
            #line 89 "..\..\Views\Admin\OrderDetails.cshtml"
    
            
            #line default
            #line hidden
            
            #line 89 "..\..\Views\Admin\OrderDetails.cshtml"
     if (User.Identity.Name == "admin" && Model.Status == OmiconShop.Domain.Enumerations.OrderStatuses.Pending)
    {
        
            
            #line default
            #line hidden
            
            #line 91 "..\..\Views\Admin\OrderDetails.cshtml"
   Write(Html.RouteLink("Approve order", new { action = "Approve", controller = "Admin", orderId = Model.OrderId },
            new { @class = "btn btn-primary" }));

            
            #line default
            #line hidden
            
            #line 92 "..\..\Views\Admin\OrderDetails.cshtml"
                                               
        
            
            #line default
            #line hidden
            
            #line 93 "..\..\Views\Admin\OrderDetails.cshtml"
   Write(Html.RouteLink("Decline order", new { action = "Decline", controller = "Admin", orderId = Model.OrderId },
            new { @class = "btn btn-primary" }));

            
            #line default
            #line hidden
            
            #line 94 "..\..\Views\Admin\OrderDetails.cshtml"
                                               
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
