#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    
    #line 2 "..\..\Views\Admin\OrderList.cshtml"
    using OmiconShop.WebUI.HtmlHelpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Admin/OrderList.cshtml")]
    public partial class _Views_Admin_OrderList_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Application.Admin.ViewModel.OrdersViewModel>
    {
        public _Views_Admin_OrderList_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Admin\OrderList.cshtml"
  
    ViewBag.Title = "OrdersList";

            
            #line default
            #line hidden
WriteLiteral("\r\n<body>\r\n    <div");

WriteLiteral(" class=\"admin-nav-menu\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 9 "..\..\Views\Admin\OrderList.cshtml"
   Write(Html.Partial("_AdminNavMenu"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div>\r\n");

            
            #line 12 "..\..\Views\Admin\OrderList.cshtml"
        
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Admin\OrderList.cshtml"
         using (Html.BeginForm("OrderList", "Admin"))
        {
            
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Admin\OrderList.cshtml"
       Write(Html.EnumDropdownListFor(x => x.SelectedStatus, Model.SelectedStatus));

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Admin\OrderList.cshtml"
                                                                                  

            
            #line default
            #line hidden
WriteLiteral("            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Ok\"");

WriteLiteral(">\r\n");

            
            #line 16 "..\..\Views\Admin\OrderList.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n    <div>\r\n        <form");

WriteLiteral(" class=\"form-inline my-2 my-lg-0\"");

WriteLiteral(">\r\n            Find by Id: ");

            
            #line 20 "..\..\Views\Admin\OrderList.cshtml"
                   Write(Html.TextBox("OrderId"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <input");

WriteLiteral(" class=\"btn btn-outline-success my-2 my-sm-0\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Search\"");

WriteLiteral(">\r\n        </form>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n            <h3>Order list</h3>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" class=\"table table-striped table-condensed table-bordered\"");

WriteLiteral(">\r\n                <tr>\r\n                    <th>Order no.</th>\r\n                " +
"    <th");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">Order date</th>\r\n                    <th");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">Bill-to name</th>\r\n                    <th");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">Total</th>\r\n                    <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">Order Satus</th>\r\n                    <th></th>\r\n                </tr>\r\n");

            
            #line 38 "..\..\Views\Admin\OrderList.cshtml"
                
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Admin\OrderList.cshtml"
                 foreach (var el in Model.Orders)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td>");

            
            #line 41 "..\..\Views\Admin\OrderList.cshtml"
                       Write(el.OrderId);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 42 "..\..\Views\Admin\OrderList.cshtml"
                                          Write(el.OrderInformation.Date);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 43 "..\..\Views\Admin\OrderList.cshtml"
                                           Write(el.User.UserPersonalInformation.Name + " " + el.User.UserPersonalInformation.Surname);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 44 "..\..\Views\Admin\OrderList.cshtml"
                                          Write(el.OrderInformation.Total);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 45 "..\..\Views\Admin\OrderList.cshtml"
                                          Write(el.Status);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 46 "..\..\Views\Admin\OrderList.cshtml"
                                          Write(Html.RouteLink("View details", new { controller = "Admin", action = "OrderDetails", orderId = el.OrderId }));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    </tr>\r\n");

            
            #line 48 "..\..\Views\Admin\OrderList.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </table>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 52 "..\..\Views\Admin\OrderList.cshtml"
       Write(Html.PageLinks(Model.PagingInfo, x => Url.Action("ProductList", new { page = x })));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</body>\r\n");

        }
    }
}
#pragma warning restore 1591
