#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_AdminLayout.cshtml")]
    public partial class _Views_Shared__AdminLayout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__AdminLayout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_AdminLayout.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <title>");

            
            #line 11 "..\..\Views\Shared\_AdminLayout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 214), Tuple.Create("\"", 239)
, Tuple.Create(Tuple.Create("", 221), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Site.css")
, 221), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 269), Tuple.Create("\"", 301)
, Tuple.Create(Tuple.Create("", 276), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ErrorStyles.css")
, 276), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" id=\"bootstrap-css\"");

WriteLiteral(">\r\n    <script");

WriteLiteral(" src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 634), Tuple.Create("\"", 665)
, Tuple.Create(Tuple.Create("", 640), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery-1.9.1.js")
, 640), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 689), Tuple.Create("\"", 723)
, Tuple.Create(Tuple.Create("", 695), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.js")
, 695), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 747), Tuple.Create("\"", 793)
, Tuple.Create(Tuple.Create("", 753), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.unobtrusive.js")
, 753), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Views\Shared\_AdminLayout.cshtml"
Write(Styles.Render("~/Content/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 21 "..\..\Views\Shared\_AdminLayout.cshtml"
Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n    <header>\r\n");

WriteLiteral("        ");

            
            #line 25 "..\..\Views\Shared\_AdminLayout.cshtml"
   Write(Html.Partial("_NavBar"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </header>\r\n\r\n");

            
            #line 28 "..\..\Views\Shared\_AdminLayout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Shared\_AdminLayout.cshtml"
     if (User.Identity.IsAuthenticated)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div>\r\n");

WriteLiteral("            ");

            
            #line 31 "..\..\Views\Shared\_AdminLayout.cshtml"
       Write(Html.RouteLink("Personal information", new { controller = "Admin", action = "PersonalInfo" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 32 "..\..\Views\Shared\_AdminLayout.cshtml"
       Write(Html.RouteLink("Orders", new { controller = "Admin", action = "OrderList" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 34 "..\..\Views\Shared\_AdminLayout.cshtml"
            
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Shared\_AdminLayout.cshtml"
             if (User.Identity.Name == "admin")
            {
                
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Shared\_AdminLayout.cshtml"
           Write(Html.RouteLink("Products", new { controller = "Admin", action = "ProductList" }));

            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Shared\_AdminLayout.cshtml"
                                                                                                 
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n");

            
            #line 39 "..\..\Views\Shared\_AdminLayout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div>\r\n");

            
            #line 42 "..\..\Views\Shared\_AdminLayout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Shared\_AdminLayout.cshtml"
         if (TempData["message"] != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"alert alert-success\"");

WriteLiteral(">");

            
            #line 44 "..\..\Views\Shared\_AdminLayout.cshtml"
                                        Write(TempData["message"]);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 45 "..\..\Views\Shared\_AdminLayout.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 46 "..\..\Views\Shared\_AdminLayout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <footer>\r\n");

WriteLiteral("        ");

            
            #line 50 "..\..\Views\Shared\_AdminLayout.cshtml"
   Write(Html.Partial("_Footer"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </footer>\r\n\r\n");

WriteLiteral("    ");

            
            #line 53 "..\..\Views\Shared\_AdminLayout.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 54 "..\..\Views\Shared\_AdminLayout.cshtml"
Write(Scripts.Render("~/bundles/bootstrap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 55 "..\..\Views\Shared\_AdminLayout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
