#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Footer.cshtml")]
    public partial class _Views_Shared__Footer_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Footer_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div>\r\n    <p>&copy; ");

            
            #line 2 "..\..\Views\Shared\_Footer.cshtml"
         Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" - Omicon-Shop</p>\r\n    <div>");

            
            #line 3 "..\..\Views\Shared\_Footer.cshtml"
    Write(Html.RouteLink("Contact us", new { controller = "Home", action = "Contact" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n    <div>");

            
            #line 4 "..\..\Views\Shared\_Footer.cshtml"
    Write(Html.RouteLink("About us", new { controller = "Home", action = "About" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
