#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Footer.cshtml")]
    public partial class _Views_Shared__Footer_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Footer_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<footer");

WriteLiteral(" class=\"page-footer font-small pt-4 bg-light fixed-bottom\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm text-center justify-content-lg-start\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"ft-link\"");

WriteLiteral(">Contact us</a>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"ft-link\"");

WriteLiteral(">About us</a>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-sm text-center justify-content-lg-center copyright\"");

WriteLiteral(">\r\n            <span>© 2019 Copyright: Omicon-shop</span>\r\n        </div>\r\n      " +
"  <div");

WriteLiteral(" class=\"col-sm text-center justify-content-lg-end\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"fab fa-facebook-f\"");

WriteLiteral("></i>\r\n            <i");

WriteLiteral(" class=\"fab fa-google\"");

WriteLiteral("></i>\r\n            <i");

WriteLiteral(" class=\"fab fa-twitter\"");

WriteLiteral("></i>\r\n            <i");

WriteLiteral(" class=\"fab fa-instagram\"");

WriteLiteral("></i>\r\n        </div>\r\n    </div>\r\n</footer>\r\n");

        }
    }
}
#pragma warning restore 1591
