#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_NavBar.cshtml"
    using Microsoft.AspNet.Identity;
    
    #line default
    #line hidden
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_NavBar.cshtml")]
    public partial class _Views_Shared__NavBar_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Application.Account.ViewModel.LoginViewModel>
    {
        public _Views_Shared__NavBar_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<nav");

WriteLiteral(" class=\"navbar navbar-expand-lg navbar-light bg-light fixed-top\"");

WriteLiteral(">\r\n    <span");

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(">Omicon-shop</span>\r\n    <button");

WriteLiteral(" class=\"navbar-toggler\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\"#navbarSupportedContent\"");

WriteLiteral(" aria-controls=\"navbarSupportedContent\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(" aria-label=\"Toggle navigation\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"navbar-toggler-icon\"");

WriteLiteral("></span>\r\n    </button>\r\n\r\n    <div");

WriteLiteral(" class=\"collapse navbar-collapse\"");

WriteLiteral(" id=\"navbarSupportedContent\"");

WriteLiteral(">\r\n        <ul");

WriteLiteral(" class=\"navbar-nav mr-auto\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" class=\"nav-item \"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 13 "..\..\Views\Shared\_NavBar.cshtml"
           Write(Html.RouteLink("All products", new { controller = "Home", action = "ProductsList" },
             new { @class = "nav-link products-link" }));

            
            #line default
            #line hidden
WriteLiteral("<span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">(current)</span>\r\n            </li>\r\n        </ul>\r\n");

            
            #line 17 "..\..\Views\Shared\_NavBar.cshtml"
        
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Shared\_NavBar.cshtml"
         using (Html.BeginForm("ProductsList", "Home", FormMethod.Get, new { @class = "form-inline my-2 my-lg-0" }))
        {

            
            #line default
            #line hidden
WriteLiteral("            <input");

WriteLiteral(" class=\"form-control mr-sm-2\"");

WriteLiteral(" type=\"search\"");

WriteLiteral(" placeholder=\"Search here...\"");

WriteLiteral(" aria-label=\"Search\"");

WriteLiteral(" name=\"productName\"");

WriteLiteral(" />\r\n");

WriteLiteral("            <button");

WriteLiteral(" class=\"btn btn-outline-success my-2 my-sm-0\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">Search</button>\r\n");

            
            #line 21 "..\..\Views\Shared\_NavBar.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        <ul");

WriteLiteral(" class=\"navbar-nav justify-content-lg-end\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" class=\"nav-item\"");

WriteLiteral(">\r\n                <i>\r\n");

WriteLiteral("                    ");

            
            #line 26 "..\..\Views\Shared\_NavBar.cshtml"
               Write(Html.RouteLink(" ", new { controller = "Basket", action = "Index", returnUrl = "Home/ProductsList" },
                   new { @class = "nav-link fas fa-shopping-basket" }));

            
            #line default
            #line hidden
WriteLiteral("<span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">(current)</span>\r\n                </i>\r\n            </li>\r\n");

            
            #line 30 "..\..\Views\Shared\_NavBar.cshtml"
            
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Shared\_NavBar.cshtml"
             if (Request.IsAuthenticated)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" class=\"nav-item dropdown\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"nav-link dropdown-toggle fas fa-user\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" id=\"navbarDropdown\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n\r\n                    </a>\r\n                    <div");

WriteLiteral(" class=\"dropdown-menu dropdown-menu-right\"");

WriteLiteral(">\r\n                        <b>");

            
            #line 37 "..\..\Views\Shared\_NavBar.cshtml"
                      Write(Html.RouteLink("My Account", new { controller = "Admin", action = "PersonalInfo" }, new { @class = "dropdown-item" }));

            
            #line default
            #line hidden
WriteLiteral("</b>\r\n                        <div");

WriteLiteral(" class=\"dropdown-divider\"");

WriteLiteral("></div>\r\n");

            
            #line 39 "..\..\Views\Shared\_NavBar.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Shared\_NavBar.cshtml"
                         using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                        {
                            
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Shared\_NavBar.cshtml"
                       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Shared\_NavBar.cshtml"
                                                    

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteLiteral(" href=\"javascript:document.getElementById(\'logoutForm\').submit()\"");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral("><b>Logoff</b></a>\r\n");

            
            #line 43 "..\..\Views\Shared\_NavBar.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </li>\r\n");

            
            #line 46 "..\..\Views\Shared\_NavBar.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" class=\"nav-item dropdown\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"nav-link dropdown-toggle login-link\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" id=\"navbarDropdown\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                        Login\r\n                    </a>\r\n                    <" +
"div");

WriteLiteral(" class=\"dropdown-menu dropdown-menu-right\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"target\"");

WriteLiteral(">");

            
            #line 54 "..\..\Views\Shared\_NavBar.cshtml"
                                    Write(Html.Partial("_LoginForm"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        <div");

WriteLiteral(" class=\"dropdown-divider\"");

WriteLiteral("></div>\r\n                        <b>");

            
            #line 56 "..\..\Views\Shared\_NavBar.cshtml"
                      Write(Html.RouteLink("Forget the password?", new { controller = "Account", action = "ChangePassword" }, new { @class = "dropdown-item" }));

            
            #line default
            #line hidden
WriteLiteral("</b>\r\n                        <b>\r\n");

WriteLiteral("                            ");

            
            #line 58 "..\..\Views\Shared\_NavBar.cshtml"
                       Write(Html.RouteLink("Register", new { controller = "Account", action = "Register" }, new { @class = "dropdown-item" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </b>\r\n                    </div>\r\n                </li>" +
"\r\n");

            
            #line 62 "..\..\Views\Shared\_NavBar.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n        </ul>\r\n    </div>\r\n</nav>");

        }
    }
}
#pragma warning restore 1591
