#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_NavBar.cshtml"
    using Microsoft.AspNet.Identity;

#line default
#line hidden
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_NavBar.cshtml")]
    public partial class _Views_Shared__NavBar_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__NavBar_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<nav");

WriteLiteral(" class=\"navbar navbar-light\"");

WriteLiteral(" style=\"background-color: #e3f2fd;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"nav-heading\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"brand\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Omicon-shop</a>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"menu\"");

WriteLiteral(" id=\"open-navbar1\"");

WriteLiteral(">\r\n            <div>");

            
            #line 9 "..\..\Views\Shared\_NavBar.cshtml"
            Write(Html.RouteLink("All products", new { controller = "Home", action = "ProductsList" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");

            
            #line 11 "..\..\Views\Shared\_NavBar.cshtml"
            
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Shared\_NavBar.cshtml"
             if (Request.IsAuthenticated)
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("\r\n                    Hello, ");

            
            #line 14 "..\..\Views\Shared\_NavBar.cshtml"
                      Write(Html.RouteLink(User.Identity.Name, new { controller = "Admin", action = "PersonalInfo" }));

            
            #line default
            #line hidden
WriteLiteral("!\r\n");

            
            #line 15 "..\..\Views\Shared\_NavBar.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Shared\_NavBar.cshtml"
                     using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                    {
                        
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Shared\_NavBar.cshtml"
                   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Shared\_NavBar.cshtml"
                                                

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteLiteral(" href=\"javascript:document.getElementById(\'logoutForm\').submit()\"");

WriteLiteral(">Log off</a>\r\n");

            
            #line 19 "..\..\Views\Shared\_NavBar.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("\r\n");

WriteLiteral("                <div>\r\n");

WriteLiteral("                    ");

            
            #line 22 "..\..\Views\Shared\_NavBar.cshtml"
               Write(Html.ActionLink("My Account", "PersonalInfo", "Admin"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 24 "..\..\Views\Shared\_NavBar.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"nav-item dropdown\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"nav-link dropdown-toggle\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" id=\"navbarDropdown\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                        Login\r\n                    </a>\r\n                    <" +
"div");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(" aria-labelledby=\"navbarDropdown\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(">");

            
            #line 32 "..\..\Views\Shared\_NavBar.cshtml"
                                            Write(Html.RouteLink("Login", new { controller = "Account", action = "Login" }));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                        <a");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(">");

            
            #line 33 "..\..\Views\Shared\_NavBar.cshtml"
                                            Write(Html.RouteLink("Register", new { controller = "Account", action = "Register" }));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                        <div");

WriteLiteral(" class=\"dropdown-divider\"");

WriteLiteral("></div>\r\n                    </div>\r\n                </div>\r\n");

            
            #line 37 "..\..\Views\Shared\_NavBar.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <div>");

            
            #line 38 "..\..\Views\Shared\_NavBar.cshtml"
            Write(Html.RouteLink("Basket", new { controller = "Basket", action = "Index", returnUrl = "Home/ProductsList" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </div>\r\n    </div>\r\n</nav>\r\n");

        }
    }
}
#pragma warning restore 1591
