#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/PageNotFound.cshtml")]
    public partial class _Views_Shared_PageNotFound_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_PageNotFound_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\PageNotFound.cshtml"
  

    ViewBag.Title = "Not found";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"col-12 page-not-found\"");

WriteLiteral(">\r\n    <hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n        <h3>THE REQUESTED PAGE CANNOT BE FOUND</h3>\r\n    </hgroup>\r\n\r\n    <div" +
"");

WriteLiteral(" class=\"page-not-found__homepage\"");

WriteLiteral(@">
        <div>
            <text>
                Sorry, we couldn't find the requested page. Maybe it's moved, or maybe the web address is incorrect. <br></br>

                Please try the following:<br>
                Check if the web address you entered is correct.<br>
            </text>
        </div>
        <div>
");

WriteLiteral("            ");

            
            #line 21 "..\..\Views\Shared\PageNotFound.cshtml"
       Write(Html.RouteLink("Go to homepage", new { controller = "Home", action = "Index" }, new { @class = "page-not-found__homepage-link" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div>\r\n            <text>\r\n                We apologize" +
" for the inconvenience.\r\n            </text>\r\n        </div>\r\n    </div>\r\n</div>" +
"");

        }
    }
}
#pragma warning restore 1591
