#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Checkout/OrderSucessfullyCreated.cshtml")]
    public partial class _Views_Checkout_OrderSucessfullyCreated_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Domain.Entities.Order>
    {
        public _Views_Checkout_OrderSucessfullyCreated_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Checkout\OrderSucessfullyCreated.cshtml"
  
    ViewBag.Title = "SucessfullOrder";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>\r\n    Dear\r\n");

            
            #line 9 "..\..\Views\Checkout\OrderSucessfullyCreated.cshtml"
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Checkout\OrderSucessfullyCreated.cshtml"
     if (User.Identity.IsAuthenticated)
    {
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Checkout\OrderSucessfullyCreated.cshtml"
Write(User.Identity.Name);

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Checkout\OrderSucessfullyCreated.cshtml"
                        }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("anonymous\r\n");

            
            #line 14 "..\..\Views\Checkout\OrderSucessfullyCreated.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    your order was sucessfully created!!!\r\n</h2>\r\n<div>\r\n");

WriteLiteral("    ");

            
            #line 18 "..\..\Views\Checkout\OrderSucessfullyCreated.cshtml"
Write(Html.RouteLink("Go to your order details",
   new { controller = "Admin", action = "OrderDetails", orderId = Model.Id}));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
