#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Checkout/OrderInformation.cshtml")]
    public partial class _Views_Checkout_OrderInformation_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Application.Checkout.ViewModel.OrderInformationViewModel>
    {
        public _Views_Checkout_OrderInformation_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Checkout\OrderInformation.cshtml"
  

    ViewBag.Title = "Checkout";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 8 "..\..\Views\Checkout\OrderInformation.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n</hgroup>\r\n\r\n");

            
            #line 11 "..\..\Views\Checkout\OrderInformation.cshtml"
 using (Html.BeginForm("OrderOverview", "Checkout"))
{
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Checkout\OrderInformation.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Checkout\OrderInformation.cshtml"
                                 
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Checkout\OrderInformation.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Checkout\OrderInformation.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Checkout\OrderInformation.cshtml"
Write(Html.EditorForModel(Model));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Checkout\OrderInformation.cshtml"
                               ;


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n        <input");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Next\"");

WriteLiteral(">\r\n    </div>\r\n");

            
            #line 20 "..\..\Views\Checkout\OrderInformation.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
