#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Checkout/OrderOverview.cshtml")]
    public partial class _Views_Checkout_OrderOverview_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Application.Basket.ViewModel.BasketViewModel>
    {
        public _Views_Checkout_OrderOverview_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Checkout\OrderOverview.cshtml"
  
    ViewBag.Title = "OrderOverview";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div>\r\n    <table>\r\n        <thead>\r\n            <tr>\r\n                <td>Pr" +
"oduct</td>\r\n                <td>Price</td>\r\n                <td>Qty</td>\r\n      " +
"          <td>Total</td>\r\n        </thead>\r\n        <tbody>\r\n");

            
            #line 17 "..\..\Views\Checkout\OrderOverview.cshtml"
            
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Checkout\OrderOverview.cshtml"
             foreach (var el in Model.Lines)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");

            
            #line 20 "..\..\Views\Checkout\OrderOverview.cshtml"
                   Write(el.Product.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 21 "..\..\Views\Checkout\OrderOverview.cshtml"
                   Write(el.Product.Price);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 22 "..\..\Views\Checkout\OrderOverview.cshtml"
                   Write(el.Quantity);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 23 "..\..\Views\Checkout\OrderOverview.cshtml"
                    Write(el.Quantity * el.Product.Price);

            
            #line default
            #line hidden
WriteLiteral("$</td>\r\n                </tr>\r\n");

            
            #line 25 "..\..\Views\Checkout\OrderOverview.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n        <tfoot>\r\n            <tr>\r\n                <td");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">Total: ");

            
            #line 29 "..\..\Views\Checkout\OrderOverview.cshtml"
                                  Write(Model.BasketTotal());

            
            #line default
            #line hidden
WriteLiteral(" $</td>\r\n            </tr>\r\n        </tfoot>\r\n    </table>\r\n</div>\r\n\r\n<div>\r\n");

WriteLiteral("    ");

            
            #line 36 "..\..\Views\Checkout\OrderOverview.cshtml"
Write(Html.RouteLink("Decline order", new { controller = "Checkout", action = "DeclineOrder", orderId = ViewBag.OrderId }, new { @class = "btn btn-primary"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 37 "..\..\Views\Checkout\OrderOverview.cshtml"
Write(Html.RouteLink("Submit order", new { controller = "Checkout", action = "SubmitOrder", orderId = ViewBag.OrderId }, new { @class = "btn btn-primary" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
