#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Checkout/OrderOverview.cshtml")]
    public partial class _Views_Checkout_OrderOverview_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Application.Basket.ViewModel.BasketViewModel>
    {
        public _Views_Checkout_OrderOverview_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Checkout\OrderOverview.cshtml"
  
    ViewBag.Title = "Order Overview";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 8 "..\..\Views\Checkout\OrderOverview.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n</hgroup>\r\n\r\n<table");

WriteLiteral(" class=\"table table table-sm col-6 order-overview-list\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><b>Product</b></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><b>Price</b></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><b>Quantity</b></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><b>UOM</b></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><b>Total</b></th>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 22 "..\..\Views\Checkout\OrderOverview.cshtml"
        
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Checkout\OrderOverview.cshtml"
         foreach (var el in Model.Lines)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 25 "..\..\Views\Checkout\OrderOverview.cshtml"
                                   Write(el.Product.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 26 "..\..\Views\Checkout\OrderOverview.cshtml"
                                    Write((double)el.Product.Price);

            
            #line default
            #line hidden
WriteLiteral(" $</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 27 "..\..\Views\Checkout\OrderOverview.cshtml"
                                   Write(el.Quantity);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 28 "..\..\Views\Checkout\OrderOverview.cshtml"
                                    Write(el.Uom);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 29 "..\..\Views\Checkout\OrderOverview.cshtml"
                                    Write(el.Quantity * (double)el.Product.Price);

            
            #line default
            #line hidden
WriteLiteral(" $</td>\r\n            </tr>\r\n");

            
            #line 31 "..\..\Views\Checkout\OrderOverview.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n    <tfoot>\r\n        <tr>\r\n            <td></td>\r\n            <td><" +
"/td>\r\n            <td></td>\r\n            <td></td>\r\n            <td");

WriteLiteral(" colspan=\"1\"");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><b>Order total:</b> ");

            
            #line 39 "..\..\Views\Checkout\OrderOverview.cshtml"
                                                               Write(Model.BasketTotal);

            
            #line default
            #line hidden
WriteLiteral(" $</td>\r\n        </tr>\r\n    </tfoot>\r\n</table>\r\n\r\n<div");

WriteLiteral(" class=\"decline-order\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 45 "..\..\Views\Checkout\OrderOverview.cshtml"
Write(Html.RouteLink("Decline order", new { controller = "Checkout", action = "DeclineOrder", id = ViewBag.OrderId },
        new { @class = "badge badge-light decline-order__decline" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"submit-order\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 50 "..\..\Views\Checkout\OrderOverview.cshtml"
Write(Html.RouteLink("Submit order", new { controller = "Checkout", action = "SubmitOrder", id = ViewBag.OrderId },
        new { @class = "badge badge-light submit-order__submit" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
