//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmiconShop.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MailTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OmiconShop.Application.Resources.MailTemplate", typeof(MailTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;font-family: verdana; font-size: 12px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;100%&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;padding-bottom: 10px; font-family: verdana; font-size: 12px;&quot;&gt;
        ///                [ProductName]
        ///            &lt;/td&gt;
        ///            &lt;td style=&quot;padding-bottom: 10px; font-family: verdana; font-size: 12px;&quot;&gt;
        ///                [Qty]
        ///            &lt;/td&gt;
        ///            &lt;td style=&quot;padding-bottom: 10px; font-family: verdana; font-size: 12px;&quot;&gt;
        ///                [Uom]
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrderConfirmation_BasketLines {
            get {
                return ResourceManager.GetString("OrderConfirmation_BasketLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;font-family: verdana; font-size: 12px;&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;100%&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;font-family: verdana; font-size: 12px;&quot;&gt;
        ///                Dear [UserName], &lt;br&gt;&lt;br&gt; Thanks for shopping at Omicon-Shop.
        ///                &lt;br&gt;
        ///                &lt;br&gt;
        ///            &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;font-family: verdana; font-size: 12px;&quot;&gt;
        ///                Your order was payed by [Payment] and will be shipped by [Delivery] [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrderConfirmation_Body {
            get {
                return ResourceManager.GetString("OrderConfirmation_Body", resourceCulture);
            }
        }
    }
}
