#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Home\_RenderProducts.cshtml"
    using OmiconShop.Domain.Enumerations;
    
    #line default
    #line hidden
    using OmiconShop.WebUI;
    
    #line 2 "..\..\Views\Home\_RenderProducts.cshtml"
    using OmiconShop.WebUI.HtmlHelpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/_RenderProducts.cshtml")]
    public partial class _Views_Home__RenderProducts_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Domain.Entities.Product>
    {
        public _Views_Home__RenderProducts_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Home\_RenderProducts.cshtml"
  
    var selectedUom = UOM.PCS;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(">\r\n        <tbody>\r\n            <tr>\r\n                ");

WriteLiteral("\r\n                <td");

WriteLiteral(" class=\"product-name\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 20 "..\..\Views\Home\_RenderProducts.cshtml"
               Write(Html.RouteLink(Model.Name, new { controller = "Home", action = "ProductDetails", productId = Model.ProductId,
                   type = ViewData["Type"], page = ViewData["Page"]}, new { @class = "badge badge-light" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td");

WriteLiteral(" class=\"description\"");

WriteLiteral(">");

            
            #line 23 "..\..\Views\Home\_RenderProducts.cshtml"
                                   Write(Model.Description);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"price\"");

WriteLiteral(">");

            
            #line 24 "..\..\Views\Home\_RenderProducts.cshtml"
                              Write((double)Model.Price);

            
            #line default
            #line hidden
WriteLiteral(" $</td>\r\n\r\n");

            
            #line 26 "..\..\Views\Home\_RenderProducts.cshtml"
                
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Home\_RenderProducts.cshtml"
                 using (Html.BeginForm("AddToCart", "Basket"))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"product-list-qty\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 29 "..\..\Views\Home\_RenderProducts.cshtml"
                   Write(Html.TextBox("Quantity", 1, new { @class = "form-control", type = "number", step = "1", min = "1" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

WriteLiteral("                    <td");

WriteLiteral(" class=\"uoms\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 32 "..\..\Views\Home\_RenderProducts.cshtml"
                   Write(Html.UomEnumDropdownList("uom", selectedUom, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

WriteLiteral("                    <td");

WriteLiteral(" class=\"add-to-card\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 35 "..\..\Views\Home\_RenderProducts.cshtml"
                   Write(Html.Hidden("productId", Model.ProductId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 36 "..\..\Views\Home\_RenderProducts.cshtml"
                   Write(Html.Hidden("returnUrl", Request.Url.PathAndQuery));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(" value=\"Add to cart\"");

WriteLiteral(">\r\n                    </td>\r\n");

            
            #line 39 "..\..\Views\Home\_RenderProducts.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n        </tbody>\r\n    </table>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
