#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    
    #line 2 "..\..\Views\Home\ProductsList.cshtml"
    using OmiconShop.WebUI.HtmlHelpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/ProductsList.cshtml")]
    public partial class _Views_Home_ProductsList_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Application.Admin.ViewModel.ProductsListViewModel>
    {
        public _Views_Home_ProductsList_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Home\ProductsList.cshtml"
  
    ViewBag.Title = "Products List";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 9 "..\..\Views\Home\ProductsList.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n</hgroup>\r\n\r\n<body>\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Views\Home\ProductsList.cshtml"
Write(Html.Action("Types", "Facet"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 15 "..\..\Views\Home\ProductsList.cshtml"
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Home\ProductsList.cshtml"
     foreach (var el in Model.Products)
    {
        
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Home\ProductsList.cshtml"
   Write(Html.Partial("_RenderProducts", el, ViewData));

            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Home\ProductsList.cshtml"
                                                      
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"btn-group pull-right\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 21 "..\..\Views\Home\ProductsList.cshtml"
   Write(Html.PageLinks(Model.PagingInfo, x => Url.Action("ProductsList", new { page = x, type = Model.Type })));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</body>\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
