#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Home\ProductDetails.cshtml"
    using OmiconShop.Application.Home.ViewModels;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Home\ProductDetails.cshtml"
    using OmiconShop.Domain.Enumerations;
    
    #line default
    #line hidden
    using OmiconShop.WebUI;
    
    #line 2 "..\..\Views\Home\ProductDetails.cshtml"
    using OmiconShop.WebUI.HtmlHelpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/ProductDetails.cshtml")]
    public partial class _Views_Home_ProductDetails_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Domain.Entities.Product>
    {
        public _Views_Home_ProductDetails_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Home\ProductDetails.cshtml"
  
    ViewBag.Title = "Product Details";
    var selectedUom = UOM.PCS;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 12 "..\..\Views\Home\ProductDetails.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n</hgroup>\r\n\r\n<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n    <div>\r\n");

WriteLiteral("        ");

            
            #line 17 "..\..\Views\Home\ProductDetails.cshtml"
   Write(Html.RouteLink("Back to overview", new { action = "ProductsList", controller = "Home", type = ViewData["Type"],
        page = ViewData["Page"]}, new { @class = "badge badge-light" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"pdp-image\"");

WriteLiteral(">\r\n");

            
            #line 22 "..\..\Views\Home\ProductDetails.cshtml"
        
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Home\ProductDetails.cshtml"
         if (Model.ImageUrl != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <img");

WriteLiteral(" class=\"pdp-img-thumbnail\"");

WriteAttribute("src", Tuple.Create(" src=\"", 686), Tuple.Create("\"", 707)
            
            #line 24 "..\..\Views\Home\ProductDetails.cshtml"
, Tuple.Create(Tuple.Create("", 692), Tuple.Create<System.Object, System.Int32>(Model.ImageUrl
            
            #line default
            #line hidden
, 692), false)
);

WriteLiteral(">\r\n");

            
            #line 25 "..\..\Views\Home\ProductDetails.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <img");

WriteLiteral(" class=\"pdp-img-thumbnail\"");

WriteAttribute("src", Tuple.Create(" src=\"", 789), Tuple.Create("\"", 828)
, Tuple.Create(Tuple.Create("", 795), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/no-image-big.png")
, 795), false)
);

WriteLiteral(">\r\n");

            
            #line 29 "..\..\Views\Home\ProductDetails.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"pdp-description\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"pdp-description__name\"");

WriteLiteral("><b>");

            
            #line 33 "..\..\Views\Home\ProductDetails.cshtml"
                                         Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</b></div>\r\n        <div");

WriteLiteral(" class=\"pdp-description__itemNo\"");

WriteLiteral("><b>Item no.:</b> ");

            
            #line 34 "..\..\Views\Home\ProductDetails.cshtml"
                                                         Write(Model.ProductId);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        <div");

WriteLiteral(" class=\"pdp-description__price\"");

WriteLiteral("><b>Price:</b> <span");

WriteLiteral(" class=\"pdp-description__price-value\"");

WriteLiteral(">");

            
            #line 35 "..\..\Views\Home\ProductDetails.cshtml"
                                                                                                 Write((double)Model.Price);

            
            #line default
            #line hidden
WriteLiteral(" $</span></div>\r\n        <div");

WriteLiteral(" class=\"pdp-description__description\"");

WriteLiteral("><b>Description:</b> ");

            
            #line 36 "..\..\Views\Home\ProductDetails.cshtml"
                                                                 Write(Model.Description);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"pdp-add-to-card-control\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"pdp-add-to-card-control__qty-label\"");

WriteLiteral("><span><b>Quantity:</b></span></div>\r\n");

            
            #line 41 "..\..\Views\Home\ProductDetails.cshtml"
        
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Home\ProductDetails.cshtml"
         using (Html.BeginForm("AddToCart", "Basket"))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"pdp-add-to-card-control__qty\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 44 "..\..\Views\Home\ProductDetails.cshtml"
           Write(Html.TextBox("Quantity", 1, new { @class = "form-control", type = "number", step = "1", min = "1" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"pdp-add-to-card-control__uom\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 47 "..\..\Views\Home\ProductDetails.cshtml"
           Write(Html.UomEnumDropdownList("uom", selectedUom, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

WriteLiteral("            <div>\r\n");

WriteLiteral("                ");

            
            #line 50 "..\..\Views\Home\ProductDetails.cshtml"
           Write(Html.Hidden("productId", Model.ProductId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 51 "..\..\Views\Home\ProductDetails.cshtml"
           Write(Html.Hidden("returnUrl", Request.Url.PathAndQuery));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success btn-lg pdp-add-to-card-control__add-to-card\"");

WriteLiteral(" value=\"Add to cart\"");

WriteLiteral(">\r\n            </div>\r\n");

            
            #line 54 "..\..\Views\Home\ProductDetails.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n\r\n    <div");

WriteLiteral(" id=\"target\"");

WriteLiteral(">\r\n");

            
            #line 58 "..\..\Views\Home\ProductDetails.cshtml"
        
            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\Home\ProductDetails.cshtml"
         using (Ajax.BeginForm("Comments", "Home", new AjaxOptions
        {
            HttpMethod = "Post",
            UpdateTargetId = "target"
        }))
        {
            
            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Home\ProductDetails.cshtml"
       Write(Html.Partial("_Comments", new CommentsViewModel(), ViewData));

            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Home\ProductDetails.cshtml"
                                                                         
            
            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\Home\ProductDetails.cshtml"
       Write(Html.Hidden("id", Model.ProductId));

            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\Home\ProductDetails.cshtml"
                                               
            
            
            #line default
            #line hidden
            
            #line 66 "..\..\Views\Home\ProductDetails.cshtml"
       Write(Html.Hidden("probability", ViewData["productProbability"]));

            
            #line default
            #line hidden
            
            #line 66 "..\..\Views\Home\ProductDetails.cshtml"
                                                                       

            
            #line default
            #line hidden
WriteLiteral("            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(" value=\"Send\"");

WriteLiteral(">\r\n");

            
            #line 68 "..\..\Views\Home\ProductDetails.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"add-this\"");

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"fab fa-facebook-f\"");

WriteLiteral("></i>\r\n        <i");

WriteLiteral(" class=\"fab fa-google\"");

WriteLiteral("></i>\r\n        <i");

WriteLiteral(" class=\"fab fa-twitter\"");

WriteLiteral("></i>\r\n        <i");

WriteLiteral(" class=\"fab fa-instagram\"");

WriteLiteral("></i>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
