#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    
    #line 2 "..\..\Views\Home\ProductsList.cshtml"
    using OmiconShop.WebUI.HtmlHelpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/ProductsList.cshtml")]
    public partial class _Views_Home_ProductsList_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Application.Admin.ViewModel.ProductsListViewModel>
    {
        public _Views_Home_ProductsList_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Home\ProductsList.cshtml"
  
    ViewBag.Title = "Product List";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 9 "..\..\Views\Home\ProductsList.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n</hgroup>\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-2 facets\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Views\Home\ProductsList.cshtml"
   Write(Html.Action("Types", "Facet"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-9 product-list\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" class=\"table table-striped admin-orders-table\"");

WriteLiteral(">\r\n");

            
            #line 19 "..\..\Views\Home\ProductsList.cshtml"
                
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Home\ProductsList.cshtml"
                 foreach (var el in Model.Products)
                {
                    
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Home\ProductsList.cshtml"
               Write(Html.Partial("_RenderProducts", el, ViewData));

            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Home\ProductsList.cshtml"
                                                                  
                }

            
            #line default
            #line hidden
WriteLiteral("            </table>\r\n        </div>\r\n        <div>\r\n            <nav>\r\n         " +
"       <input");

WriteLiteral(" class=\"current-page\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 760), Tuple.Create("\"", 797)
            
            #line 27 "..\..\Views\Home\ProductsList.cshtml"
, Tuple.Create(Tuple.Create("", 768), Tuple.Create<System.Object, System.Int32>(Model.PagingInfo.CurrentPage
            
            #line default
            #line hidden
, 768), false)
);

WriteLiteral(">\r\n                <input");

WriteLiteral(" class=\"total-pages\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 857), Tuple.Create("\"", 893)
            
            #line 28 "..\..\Views\Home\ProductsList.cshtml"
, Tuple.Create(Tuple.Create("", 865), Tuple.Create<System.Object, System.Int32>(Model.PagingInfo.TotalPages
            
            #line default
            #line hidden
, 865), false)
);

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"pagination justify-content-end\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 30 "..\..\Views\Home\ProductsList.cshtml"
               Write(Html.PageLinks(Model.PagingInfo, x => Url.Action("ProductsList", new { page = x, type = Model.Type })));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </ul>\r\n            </nav>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
