#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ChangePassword.cshtml")]
    public partial class _Views_Account_ChangePassword_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Application.Account.ViewModel.ChangePasswordViewModel>
    {
        public _Views_Account_ChangePassword_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\ChangePassword.cshtml"
  
    ViewBag.Title = "ChangePassword";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 8 "..\..\Views\Account\ChangePassword.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n</hgroup>\r\n\r\n<p");

WriteLiteral(" class=\"message-success\"");

WriteLiteral(">");

            
            #line 11 "..\..\Views\Account\ChangePassword.cshtml"
                      Write(ViewBag.StatusMessage);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n<p>You\'re logged in as <strong>");

            
            #line 12 "..\..\Views\Account\ChangePassword.cshtml"
                          Write(User.Identity.Name);

            
            #line default
            #line hidden
WriteLiteral("</strong>.</p>\r\n\r\n<section");

WriteLiteral(" id=\"changePasswordForm\"");

WriteLiteral(">\r\n");

            
            #line 15 "..\..\Views\Account\ChangePassword.cshtml"
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Account\ChangePassword.cshtml"
     using (Html.BeginForm())
    {
        
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Account\ChangePassword.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Account\ChangePassword.cshtml"
                                
        
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Account\ChangePassword.cshtml"
   Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Account\ChangePassword.cshtml"
                                     


            
            #line default
            #line hidden
WriteLiteral("        <fieldset>\r\n            <legend>Change Password Form</legend>\r\n          " +
"  <ol>\r\n                <li>\r\n");

WriteLiteral("                    ");

            
            #line 24 "..\..\Views\Account\ChangePassword.cshtml"
               Write(Html.LabelFor(m => m.OldPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 25 "..\..\Views\Account\ChangePassword.cshtml"
               Write(Html.TextBoxFor(m => m.OldPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 26 "..\..\Views\Account\ChangePassword.cshtml"
               Write(Html.ValidationMessageFor(m => m.OldPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n");

WriteLiteral("                    ");

            
            #line 29 "..\..\Views\Account\ChangePassword.cshtml"
               Write(Html.LabelFor(m => m.NewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 30 "..\..\Views\Account\ChangePassword.cshtml"
               Write(Html.TextBoxFor(m => m.NewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 31 "..\..\Views\Account\ChangePassword.cshtml"
               Write(Html.ValidationMessageFor(m => m.NewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n");

WriteLiteral("                    ");

            
            #line 34 "..\..\Views\Account\ChangePassword.cshtml"
               Write(Html.LabelFor(m => m.ConfirmNewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 35 "..\..\Views\Account\ChangePassword.cshtml"
               Write(Html.TextBoxFor(m => m.ConfirmNewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 36 "..\..\Views\Account\ChangePassword.cshtml"
               Write(Html.ValidationMessageFor(m => m.ConfirmNewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n            </ol>\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Submit\"");

WriteLiteral(">\r\n        </fieldset>\r\n");

            
            #line 41 "..\..\Views\Account\ChangePassword.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</section>\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 45 "..\..\Views\Account\ChangePassword.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
