#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Register.cshtml")]
    public partial class _Views_Account_Register_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Application.Account.ViewModel.RegisterViewModel>
    {
        public _Views_Account_Register_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\Register.cshtml"
  
    ViewBag.Title = "Registration";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 8 "..\..\Views\Account\Register.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n</hgroup>\r\n\r\n<section");

WriteLiteral(" id=\"registerForm\"");

WriteLiteral(">\r\n");

            
            #line 12 "..\..\Views\Account\Register.cshtml"
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Account\Register.cshtml"
     using (Html.BeginForm(new { ReturnUrl = ViewBag.ReturnUrl }))
    {
        
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Account\Register.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Account\Register.cshtml"
                                
        
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Account\Register.cshtml"
   Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Account\Register.cshtml"
                                     


            
            #line default
            #line hidden
WriteLiteral("        <fieldset>\r\n            <legend>Log in Form</legend>\r\n");

WriteLiteral("            ");

            
            #line 19 "..\..\Views\Account\Register.cshtml"
       Write(Html.EditorForModel());

            
            #line default
            #line hidden
WriteLiteral("\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Register\"");

WriteLiteral(">\r\n        </fieldset>\r\n");

            
            #line 22 "..\..\Views\Account\Register.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n</section>\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 30 "..\..\Views\Account\Register.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
