#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Register.cshtml")]
    public partial class _Views_Account_Register_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Application.Account.ViewModel.RegisterViewModel>
    {
        public _Views_Account_Register_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\Register.cshtml"
  
    ViewBag.Title = "Registration";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 8 "..\..\Views\Account\Register.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n</hgroup>\r\n\r\n<section");

WriteLiteral(" id=\"registerForm\"");

WriteLiteral(">\r\n");

            
            #line 12 "..\..\Views\Account\Register.cshtml"
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Account\Register.cshtml"
     using (Html.BeginForm(new { ReturnUrl = ViewBag.ReturnUrl }))
    {
        
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Account\Register.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Account\Register.cshtml"
                                
        
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Account\Register.cshtml"
   Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Account\Register.cshtml"
                                     


            
            #line default
            #line hidden
WriteLiteral("        <fieldset>\r\n            <legend>Log in Form</legend>\r\n            <ol>\r\n " +
"               <li>\r\n");

WriteLiteral("                    ");

            
            #line 21 "..\..\Views\Account\Register.cshtml"
               Write(Html.LabelFor(m => m.Login));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 22 "..\..\Views\Account\Register.cshtml"
               Write(Html.TextBoxFor(m => m.Login));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 23 "..\..\Views\Account\Register.cshtml"
               Write(Html.ValidationMessageFor(m => m.Login));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n");

WriteLiteral("                    ");

            
            #line 26 "..\..\Views\Account\Register.cshtml"
               Write(Html.LabelFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 27 "..\..\Views\Account\Register.cshtml"
               Write(Html.TextBoxFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 28 "..\..\Views\Account\Register.cshtml"
               Write(Html.ValidationMessageFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n");

WriteLiteral("                    ");

            
            #line 31 "..\..\Views\Account\Register.cshtml"
               Write(Html.LabelFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 32 "..\..\Views\Account\Register.cshtml"
               Write(Html.TextBoxFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 33 "..\..\Views\Account\Register.cshtml"
               Write(Html.ValidationMessageFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n");

WriteLiteral("                    ");

            
            #line 36 "..\..\Views\Account\Register.cshtml"
               Write(Html.LabelFor(m => m.RememberMe, new { @class = "checkbox" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 37 "..\..\Views\Account\Register.cshtml"
               Write(Html.CheckBoxFor(m => m.RememberMe));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n            </ol>\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Register\"");

WriteLiteral(">\r\n        </fieldset>\r\n");

            
            #line 42 "..\..\Views\Account\Register.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <p>\r\n");

WriteLiteral("        ");

            
            #line 45 "..\..\Views\Account\Register.cshtml"
   Write(Html.RouteLink("Log in", new { controller = "Action", action = "Login" }));

            
            #line default
            #line hidden
WriteLiteral(" if you have an account!\r\n    </p>\r\n</section>\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 50 "..\..\Views\Account\Register.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
