#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Basket/Index.cshtml")]
    public partial class _Views_Basket_Index_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Application.Basket.ViewModel.BasketIndexViewModel>
    {
        public _Views_Basket_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Basket\Index.cshtml"
  
    ViewBag.Title = "Shopping cart";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 7 "..\..\Views\Basket\Index.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n</hgroup>\r\n\r\n<input");

WriteLiteral(" class=\"lines-count\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 222), Tuple.Create("\"", 257)
            
            #line 10 "..\..\Views\Basket\Index.cshtml"
, Tuple.Create(Tuple.Create("", 230), Tuple.Create<System.Object, System.Int32>(Model.Basket.Lines.Count()
            
            #line default
            #line hidden
, 230), false)
);

WriteLiteral(">\r\n<div");

WriteLiteral(" class=\"shopping-cart-list\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"basketItems\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"\"");

WriteLiteral(@">
                    <div></div>
                    <span><b>Product</b></span>
                    <span><b>Price</b></span>
                    <span><b>Quantity</b></span>
                    <span><b>UOM</b></span>
                    <span><b>Total</b></span>
                </div>
            </div>
            <div>
");

            
            #line 24 "..\..\Views\Basket\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Basket\Index.cshtml"
                 foreach (var el in Model.Basket.Lines)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 815), Tuple.Create("\"", 856)
, Tuple.Create(Tuple.Create("", 823), Tuple.Create("row-", 823), true)
            
            #line 26 "..\..\Views\Basket\Index.cshtml"
, Tuple.Create(Tuple.Create("", 827), Tuple.Create<System.Object, System.Int32>(el.Product.ProductId
            
            #line default
            #line hidden
, 827), false)
, Tuple.Create(Tuple.Create("", 848), Tuple.Create("-", 848), true)
            
            #line 26 "..\..\Views\Basket\Index.cshtml"
, Tuple.Create(Tuple.Create("", 849), Tuple.Create<System.Object, System.Int32>(el.Uom
            
            #line default
            #line hidden
, 849), false)
);

WriteLiteral(">\r\n                        <div>\r\n");

            
            #line 28 "..\..\Views\Basket\Index.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Basket\Index.cshtml"
                             if (el.Product.ImageUrl != null)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <img");

WriteLiteral(" class=\"img-thumbnail\"");

WriteLiteral(" width=\"30\"");

WriteLiteral(" height=\"30\"");

WriteAttribute("src", Tuple.Create("\r\n                                     src=\"", 1066), Tuple.Create("\"", 1130)
            
            #line 31 "..\..\Views\Basket\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1110), Tuple.Create<System.Object, System.Int32>(el.Product.ImageUrl
            
            #line default
            #line hidden
, 1110), false)
);

WriteLiteral(">\r\n");

            
            #line 32 "..\..\Views\Basket\Index.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                        <div>");

            
            #line 34 "..\..\Views\Basket\Index.cshtml"
                        Write(el.Product.Name);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        <div>");

            
            #line 35 "..\..\Views\Basket\Index.cshtml"
                         Write((double)el.Product.Price);

            
            #line default
            #line hidden
WriteLiteral("$</div>\r\n                        <div>\r\n");

WriteLiteral("                            ");

            
            #line 37 "..\..\Views\Basket\Index.cshtml"
                       Write(Html.TextBox("Quantity", el.Quantity, new { @data_product_id = el.Product.ProductId,
                           @data_product_uom = el.Uom, @data_product_price = el.Product.Price,
                           @class = "form-control qty", type = "number", step = "1", min = "1" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div>");

            
            #line 41 "..\..\Views\Basket\Index.cshtml"
                         Write(el.Uom);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 1762), Tuple.Create("\"", 1805)
, Tuple.Create(Tuple.Create("", 1770), Tuple.Create("total-", 1770), true)
            
            #line 42 "..\..\Views\Basket\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1776), Tuple.Create<System.Object, System.Int32>(el.Product.ProductId
            
            #line default
            #line hidden
, 1776), false)
, Tuple.Create(Tuple.Create("", 1797), Tuple.Create("-", 1797), true)
            
            #line 42 "..\..\Views\Basket\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1798), Tuple.Create<System.Object, System.Int32>(el.Uom
            
            #line default
            #line hidden
, 1798), false)
);

WriteLiteral(">");

            
            #line 42 "..\..\Views\Basket\Index.cshtml"
                                                                     Write(el.Quantity * (double)el.Product.Price);

            
            #line default
            #line hidden
WriteLiteral("$</div>\r\n                        <div>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"link-remove\"");

WriteLiteral(" data-id=\"");

            
            #line 44 "..\..\Views\Basket\Index.cshtml"
                                                                Write(el.Product.ProductId);

            
            #line default
            #line hidden
WriteLiteral("-");

            
            #line 44 "..\..\Views\Basket\Index.cshtml"
                                                                                      Write(el.Uom);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">Delete</a>\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 47 "..\..\Views\Basket\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"basket-summary\"");

WriteLiteral(">\r\n    <b>Summary:</b><span");

WriteLiteral(" class=\"basket-summary__value\"");

WriteLiteral(">");

            
            #line 53 "..\..\Views\Basket\Index.cshtml"
                                                  Write(Model.Basket.BasketTotal);

            
            #line default
            #line hidden
WriteLiteral(" $</span>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"empty-basket\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" class=\"badge badge-light btn-emptyBasket\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Empty basket</a>\r\n</div>\r\n<div");

WriteLiteral(" class=\"basket-buttons\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" class=\"badge badge-light btn-returnUrl\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2444), Tuple.Create("\"", 2467)
            
            #line 60 "..\..\Views\Basket\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2451), Tuple.Create<System.Object, System.Int32>(Model.RetunrUrl
            
            #line default
            #line hidden
, 2451), false)
);

WriteLiteral(">Continue shopping</a>\r\n");

WriteLiteral("    ");

            
            #line 61 "..\..\Views\Basket\Index.cshtml"
Write(Html.RouteLink("Procceed to checkout", new { action = "OrderInformation", controller = "Checkout" },
        new {@class = "badge badge-light btn-procceedToCheckout" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
