#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Basket/Index.cshtml")]
    public partial class _Views_Basket_Index_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Application.Basket.ViewModel.BasketIndexViewModel>
    {
        public _Views_Basket_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Basket\Index.cshtml"
  
    ViewBag.Title = "Index";

            
            #line default
            #line hidden
WriteLiteral(@"

<h2>Your basket</h2>
<div>
    <table>
        <thead>
            <tr>
                <th></th>
                <th>Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>UOM</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>

");

            
            #line 21 "..\..\Views\Basket\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Basket\Index.cshtml"
             foreach (var el in Model.Basket.Lines)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr");

WriteAttribute("id", Tuple.Create(" id=\"", 518), Tuple.Create("\"", 556)
, Tuple.Create(Tuple.Create("", 523), Tuple.Create("row-", 523), true)
            
            #line 23 "..\..\Views\Basket\Index.cshtml"
, Tuple.Create(Tuple.Create("", 527), Tuple.Create<System.Object, System.Int32>(el.Product.ProductId
            
            #line default
            #line hidden
, 527), false)
, Tuple.Create(Tuple.Create("", 548), Tuple.Create("-", 548), true)
            
            #line 23 "..\..\Views\Basket\Index.cshtml"
, Tuple.Create(Tuple.Create("", 549), Tuple.Create<System.Object, System.Int32>(el.Uom
            
            #line default
            #line hidden
, 549), false)
);

WriteLiteral(">\r\n");

            
            #line 24 "..\..\Views\Basket\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Basket\Index.cshtml"
                     if (el.Product.ImageUrl != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <td>\r\n                            <img");

WriteLiteral(" class=\"img-thumbnail\"");

WriteLiteral(" width=\"30\"");

WriteLiteral(" height=\"30\"");

WriteAttribute("src", Tuple.Create("\r\n                                 src=\"", 745), Tuple.Create("\"", 805)
            
            #line 28 "..\..\Views\Basket\Index.cshtml"
, Tuple.Create(Tuple.Create("", 785), Tuple.Create<System.Object, System.Int32>(el.Product.ImageUrl
            
            #line default
            #line hidden
, 785), false)
);

WriteLiteral(">\r\n                        </td>\r\n");

            
            #line 30 "..\..\Views\Basket\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <td>");

            
            #line 32 "..\..\Views\Basket\Index.cshtml"
                   Write(el.Product.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 33 "..\..\Views\Basket\Index.cshtml"
                   Write(el.Product.Price);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    ");

WriteLiteral("\r\n                    <td>");

            
            #line 37 "..\..\Views\Basket\Index.cshtml"
                   Write(el.Quantity);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 38 "..\..\Views\Basket\Index.cshtml"
                    Write(el.Uom);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 39 "..\..\Views\Basket\Index.cshtml"
                    Write(el.Quantity * el.Product.Price);

            
            #line default
            #line hidden
WriteLiteral("$</td>\r\n                    <td>\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"RemoveLink\"");

WriteLiteral(" data-id=\"");

            
            #line 41 "..\..\Views\Basket\Index.cshtml"
                                                           Write(el.Product.ProductId);

            
            #line default
            #line hidden
WriteLiteral("-");

            
            #line 41 "..\..\Views\Basket\Index.cshtml"
                                                                                 Write(el.Uom);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">Delete</a>\r\n                    </td>\r\n                </tr>\r\n");

            
            #line 44 "..\..\Views\Basket\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n        </tbody>\r\n        <tfoot>\r\n            <tr>\r\n                <td");

WriteLiteral(" id=\"cart-status\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">Summary: ");

            
            #line 49 "..\..\Views\Basket\Index.cshtml"
                                                     Write(Model.Basket.BasketTotal);

            
            #line default
            #line hidden
WriteLiteral(" $</td>\r\n            </tr>\r\n        </tfoot>\r\n    </table>\r\n</div>\r\n<div>\r\n");

            
            #line 55 "..\..\Views\Basket\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Basket\Index.cshtml"
     using (Html.BeginForm("EmptyBasket", "Basket"))
    {
        
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Basket\Index.cshtml"
   Write(Html.Hidden("returnUrl", Model.RetunrUrl));

            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Basket\Index.cshtml"
                                                  

            
            #line default
            #line hidden
WriteLiteral("        <input");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Empty basket\"");

WriteLiteral(">\r\n");

            
            #line 59 "..\..\Views\Basket\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div>\r\n    <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1970), Tuple.Create("\"", 1993)
            
            #line 62 "..\..\Views\Basket\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1977), Tuple.Create<System.Object, System.Int32>(Model.RetunrUrl
            
            #line default
            #line hidden
, 1977), false)
);

WriteLiteral(">Continue shopping</a>\r\n");

WriteLiteral("    ");

            
            #line 63 "..\..\Views\Basket\Index.cshtml"
Write(Html.RouteLink("Procceed to checkout", new { action = "OrderInformation", controller = "Checkout" }, new { @class = "btn btn-primary" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<script");

WriteLiteral(" src=\"/Scripts/jquery-1.4.4.min.js\"");

WriteLiteral("\r\n        type=\"text/javascript\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    $(function () {
        $("".RemoveLink"").click(function () {
            var product = $(this).attr(""data-id"");
            if (product != null) {
                $.post(""Basket/RemoveFromBasket"", { ""productInfo"": product },
                    function (data) {
                        $('#row-' + product).fadeOut('slow');
                        $('#cart-status').text(""Summary: "" + data.BasketTotal + "" $"");
                    });
            }
        });
    });
</script>
");

        }
    }
}
#pragma warning restore 1591
