#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using OmiconShop.WebUI;
    using OmiconShop.WebUI.HtmlHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Basket/Index.cshtml")]
    public partial class _Views_Basket_Index_cshtml : System.Web.Mvc.WebViewPage<OmiconShop.Application.Basket.ViewModel.BasketIndexViewModel>
    {
        public _Views_Basket_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Basket\Index.cshtml"
  
    ViewBag.Title = "Index";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <h2>Your basket</h2>\r\n    <div>\r\n        <table");

WriteLiteral(" id=\"basketItems\"");

WriteLiteral(@">
            <thead>
                <tr>
                    <th></th>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>UOM</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
");

            
            #line 20 "..\..\Views\Basket\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Basket\Index.cshtml"
                 foreach (var el in Model.Basket.Lines)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr");

WriteAttribute("id", Tuple.Create(" id=\"", 601), Tuple.Create("\"", 639)
, Tuple.Create(Tuple.Create("", 606), Tuple.Create("row-", 606), true)
            
            #line 22 "..\..\Views\Basket\Index.cshtml"
, Tuple.Create(Tuple.Create("", 610), Tuple.Create<System.Object, System.Int32>(el.Product.ProductId
            
            #line default
            #line hidden
, 610), false)
, Tuple.Create(Tuple.Create("", 631), Tuple.Create("-", 631), true)
            
            #line 22 "..\..\Views\Basket\Index.cshtml"
, Tuple.Create(Tuple.Create("", 632), Tuple.Create<System.Object, System.Int32>(el.Uom
            
            #line default
            #line hidden
, 632), false)
);

WriteLiteral(">\r\n");

            
            #line 23 "..\..\Views\Basket\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Basket\Index.cshtml"
                         if (el.Product.ImageUrl != null)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <td>\r\n                                <img");

WriteLiteral(" class=\"img-thumbnail\"");

WriteLiteral(" width=\"30\"");

WriteLiteral(" height=\"30\"");

WriteAttribute("src", Tuple.Create("\r\n                                     src=\"", 844), Tuple.Create("\"", 908)
            
            #line 27 "..\..\Views\Basket\Index.cshtml"
, Tuple.Create(Tuple.Create("", 888), Tuple.Create<System.Object, System.Int32>(el.Product.ImageUrl
            
            #line default
            #line hidden
, 888), false)
);

WriteLiteral(">\r\n                            </td>\r\n");

            
            #line 29 "..\..\Views\Basket\Index.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <td>");

            
            #line 30 "..\..\Views\Basket\Index.cshtml"
                       Write(el.Product.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>");

            
            #line 31 "..\..\Views\Basket\Index.cshtml"
                       Write(el.Product.Price);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td");

WriteLiteral(" class=\"uom\"");

WriteLiteral(" width=\"80px\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 33 "..\..\Views\Basket\Index.cshtml"
                       Write(Html.TextBox("Quantity", el.Quantity, new { @class = "form-control", type = "number", step = "1", min = "1" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>");

            
            #line 35 "..\..\Views\Basket\Index.cshtml"
                        Write(el.Uom);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>");

            
            #line 36 "..\..\Views\Basket\Index.cshtml"
                        Write(el.Quantity * (double)el.Product.Price);

            
            #line default
            #line hidden
WriteLiteral("$</td>\r\n                        <td>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"RemoveLink\"");

WriteLiteral(" data-id=\"");

            
            #line 38 "..\..\Views\Basket\Index.cshtml"
                                                               Write(el.Product.ProductId);

            
            #line default
            #line hidden
WriteLiteral("-");

            
            #line 38 "..\..\Views\Basket\Index.cshtml"
                                                                                     Write(el.Uom);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">Delete</a>\r\n                        </td>\r\n                    </tr>\r\n");

            
            #line 41 "..\..\Views\Basket\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n            <tfoot>\r\n                <tr>\r\n                " +
"    <td");

WriteLiteral(" id=\"cart-status\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">Summary: ");

            
            #line 45 "..\..\Views\Basket\Index.cshtml"
                                                         Write(Model.Basket.BasketTotal);

            
            #line default
            #line hidden
WriteLiteral(" $</td>\r\n                </tr>\r\n            </tfoot>\r\n        </table>\r\n    </div" +
">\r\n    <div>\r\n        <input");

WriteLiteral(" id=\"recalculate\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Recalculate shopping cart\"");

WriteLiteral(" />\r\n    </div>\r\n\r\n<div>\r\n    <input");

WriteLiteral(" id=\"emptyBasket\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" value=\"Empty basket\"");

WriteLiteral(">\r\n</div>\r\n<div>\r\n    <a");

WriteLiteral(" id=\"returnUrl\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2160), Tuple.Create("\"", 2183)
            
            #line 58 "..\..\Views\Basket\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2167), Tuple.Create<System.Object, System.Int32>(Model.RetunrUrl
            
            #line default
            #line hidden
, 2167), false)
);

WriteLiteral(">Continue shopping</a>\r\n");

WriteLiteral("    ");

            
            #line 59 "..\..\Views\Basket\Index.cshtml"
Write(Html.RouteLink("Procceed to checkout", new { action = "OrderInformation", controller = "Checkout" },
        new { id = "procceedToCheckout", @class = "btn btn-primary" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n\r\n<script");

WriteLiteral(" src=\"/Scripts/jquery-1.4.4.min.js\"");

WriteLiteral("\r\n        type=\"text/javascript\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    $(function () {
        $("".RemoveLink"").click(function () {
            var product = $(this).attr(""data-id"");
            if (product != null) {
                $.post(""Basket/RemoveFromBasket"", { ""productInfo"": product },
                    function (data) {
                        $('#row-' + product).fadeOut('slow');
                        $('#cart-status').text(""Summary: "" + data.BasketTotal + "" $"");
                    });
            }
        });
    });
</script>

<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(function () {\r\n        $(\"#emptyBasket\").click(function () {\r\n          " +
"  $.post(\"Basket/EmptyBasket\", {\"returnUrl\": ");

            
            #line 84 "..\..\Views\Basket\Index.cshtml"
                                                  Write(Model.RetunrUrl);

            
            #line default
            #line hidden
WriteLiteral("},\r\n                function (data) {\r\n                    $(\'#basketItems\').empt" +
"y();\r\n                    $(\'#cart-status\').text(\"Summary: \" + data.BasketTotal " +
"+ \" $\");\r\n                });\r\n        });\r\n    });\r\n</script>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    $(function () {
        $("".uom"").change(function () {
            $(""#recalculate"").show();
            $(""#emptyBasket"").addClass('disabled');
            $(""#returnUrl"").addClass('disabled');
            $(""#procceedToCheckout"").addClass('disabled');
        });
    });
</script>

<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    $(function () {
        $(""#recalculate"").click(function () {
            $.post(""Basket/RecalculateBasket"",
                function (data) {
                    $(""#recalculate"").hide();
                    $(""#emptyBasket"").removeClass('disabled');
                    $(""#returnUrl"").removeClass('disabled');
                    $(""#procceedToCheckout"").removeClass('disabled');
                    $('#cart-status').text(""Summary: "" + data.BasketTotal + "" $"");
                });
        });
    });
</script>");

        }
    }
}
#pragma warning restore 1591
